# fly.toml file generated for bot-manager on 2022-12-23T00:35:34-03:00

app = "bot-manager"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[build.args]
  PB_VERSION="0.10.1"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 5679
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8080
